#!/bin/bash

IMAGE="pmelegend/portcat:latest"

container=$(docker ps -a -q --filter ancestor=$IMAGE --format="{{.ID}}")
[ ! -z "$container" ] && docker rm $(docker stop $container)

if [[ "$(docker images -q $IMAGE 2> /dev/null)" == "" ]]; then
  docker image rm $IMAGE
fi

docker build -t $IMAGE .
