#!/bin/bash

TAG="portcat"
NAME="alpine-portcat"

TARGET="$1"
PORTS=${@:2}

if [ ! -z "$TARGET" ]; then
  container=$(docker ps -a -q --filter ancestor=$TAG --format="{{.ID}}")
  [ ! -z "$container" ] && docker rm $(docker stop $container)

  ipAddress=$(docker inspect $TARGET 2> /dev/null | grep IPAddress | grep -o '[0-9]\{1,3\}\(\.[0-9]\{1,3\}\)\{3\}' | head -n 1)
  if [ ! -z "$ipAddress" ]; then
    ports=""
    for port in ${PORTS[@]}; do
      from=$(echo "$port" | cut -d":" -f 1)
      ports="$ports -p $from:$from"
    done
    exec docker run$ports --name=$NAME -it $TAG $ipAddress ${PORTS}
  fi
fi
