#!/bin/bash

IP=$1
PORTS=${@:2}

for port in ${PORTS[@]}; do
  from=$(echo "$port" | cut -d":" -f 1)
  to=$(echo "$port" | cut -d":" -f 2)
  socat TCP4-LISTEN:$from,fork TCP4:$IP:$to &
done

ps aux
exec bash
